/* Generated By:JavaCC: Do not edit this line. ejercicio11Constants.java */
package problemario.ejercicio11;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ejercicio11Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUMERO_ENTERO = 1;
  /** RegularExpression Id. */
  int ENTERO_ACEPTADO = 2;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<NUMERO_ENTERO>",
    "<ENTERO_ACEPTADO>",
  };

}
