/* Generated By:JavaCC: Do not edit this line. ejercicio11Constants.java */
package problemario.ejercicio11;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ejercicio11Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUMEROENTERO = 5;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<NUMEROENTERO>",
  };

}
