/* Generated By:JavaCC: Do not edit this line. ejercicio3Constants.java */
package problemario.ejercicio3;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ejercicio3Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int RELACIONALES = 5;
  /** RegularExpression Id. */
  int MENORQUE = 6;
  /** RegularExpression Id. */
  int MAYORQUE = 7;
  /** RegularExpression Id. */
  int MENORIGUAL = 8;
  /** RegularExpression Id. */
  int MAYORIGUAL = 9;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<RELACIONALES>",
    "<MENORQUE>",
    "<MAYORQUE>",
    "\"<=\"",
    "\">=\"",
  };

}
