PARSE_BEGIN (test)
class test
public static void main (String [] args) throws ParseException
    {
try
{
test analizador== new test (System.in);
analizador.Programa ();
System.out.println ("Se ha compilado con exito");
} 
catch (ParseException e)
{
System.out.println (e.getMessage());
System.out.println ("Se han encontrado errores");
}
    }
PARSE_END (test)

TOKEN:
{
<MAIN: "public static void Main ()"> {System.out.println ("MAIN" ->"+image);}
<PROGRAMA: "Programa" > {System.out.println ("PROGRAMA ->"+image);}
<IF "ien" > {System.out.println ("IF ->"+image);}
}
TOKEN:

{
    <LPAREN: "(" > {System.out.println("LPAREN ->"+image);}
    |   <RPAREN: ")" > {System.out.println("DPAREN ->"+image);}
    |   <LBRACE: "{" > {System.out.println("ILLAVE ->"+image);}
    |   <RBRACE: "}" > {System.out.println("DLLAVE ->"+image);}
    |   <SEMICOLON: ";" > {System.out.println("PUNTO Y COMA ->"+image);}
}
TOKEN: 
{ 
<ASIGNACION: "=" > {System.out.print.ln("ASIGNACION ->"+image+"\r\n");}
<MENOR: "<" > {System.out.print.ln("MENOR QUE ->"+image);}
<MAYOR: ">" > {System.out.print.ln("MAYOR QUE ->"+image);}
}
TOKEN: 
{
<INT: "inum" > {System.out.print.ln("ASIGNACION ->"+image+"\r\n");}
<NUMBER: (["0"-"9"])+ > {System.out.print.ln("NUMERO ->"+image+"\r\n");}
<IDENTIFIER: ["a"-"z","A"-"Z"] (["a"-"z","A"-"Z","0"-"9","_"]){0,47}*> {System.out.print.ln("NOMBREVARIABLE ->"+image+"\r\n");}
}
SKIP:
{
" " | "\r\n" | "\t"
}

Void programa () :
{}
{
<PROGRAMA><IDENTIFIER><LBRACE>Principal () <RBRACE><EOF>
}