/* Generated By:JavaCC: Do not edit this line. tarea3Constants.java */
package problemarioGramaticas.tarea01;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface tarea3Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMILLAS = 5;
  /** RegularExpression Id. */
  int PARENTESIS_IZQUIERDO = 6;
  /** RegularExpression Id. */
  int PARENTESIS_DERECHO = 7;
  /** RegularExpression Id. */
  int ESCRIBE = 8;
  /** RegularExpression Id. */
  int LEER = 9;
  /** RegularExpression Id. */
  int CADENA = 10;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\\"\"",
    "\"(\"",
    "\")\"",
    "<ESCRIBE>",
    "<LEER>",
    "<CADENA>",
  };

}
